# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'AgmaSdkIos', :git => 'https://github.com/agma-dna/agma-sdk-ios.git', :tag => '1.2.0'
  pod 'PrebidMobile', '~> 2.4.0'
end
